/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.pucmm.eict.csbt.gui;

import edu.pucmm.eict.csbt.servicios.ServidorComunicacion;
import edu.pucmm.eict.csbt.util.IObserver;
import edu.pucmm.eict.csbt.util.TipoNotificacion;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class JFServidor extends javax.swing.JFrame {

    //
    private int conectados = 0;
    
    /**
     * Creates new form JFServidor
     */
    public JFServidor() {
        initComponents();
    }

    private void iniciar() {
        try {
            btnInicioParada.setText("Parar");
            btnInicioParada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/stop.png")));
            //obteniendo el puerto:
            int puerto = Integer.parseInt(txtPuerto.getText());            
            //subscribiendo a los eventos del servidor.
            ServidorComunicacion.getInstacia().addObservadorListener((Class clase, Object argumento, Enum anEnum) -> {
                eventosServidor(clase, argumento, anEnum);
            });
            //iniciando el servicio.
            ServidorComunicacion.getInstacia().iniciarServidor(puerto);
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Error: " + e.getMessage());
        }
    }
    
    /**
     * 
     * @param clase
     * @param argumento
     * @param anEnum 
     */
    public void eventosServidor(Class clase, Object argumento, Enum anEnum){
        TipoNotificacion tn = (TipoNotificacion) anEnum;
                switch (tn) {
                    case LOG:
                        taLog.append((String) argumento + "\n");
                        break;
                    case CONEXION:
                        conectados++;
                        taLog.append("Nuevo Cliente Conectado: "+conectados);
                        break;
                    case DESCONEXION:
                        conectados--;
                        taLog.append("Cliente Des-conectado: "+conectados);                        
                        break;
                    default:
                        System.out.println("Valor recibido no programado");
                }
    }

    /**
     *
     */
    private void parar() {
        btnInicioParada.setText("Iniciar");
        btnInicioParada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/conectado.png")));
        System.out.println("Parando el servido vista...");
        ServidorComunicacion.getInstacia().pararServidor();
    }

    /**
     *
     */
    private void procesoInicioParar() {
        if (btnInicioParada.isSelected()) {
            iniciar();
        } else {
            parar();
        }
    }

    /**
     *
     */
    private void limpiarLogs() {
        taLog.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();
        btnLimpiarLog = new javax.swing.JButton();
        btnInicioParada = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor Clone IRC");

        jLabel1.setText("Puerto Servidor:");

        btnLimpiarLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiarlog.png"))); // NOI18N
        btnLimpiarLog.setText("Limpiar Log");
        btnLimpiarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarLogActionPerformed(evt);
            }
        });

        btnInicioParada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/conectado.png"))); // NOI18N
        btnInicioParada.setText("Inicio");
        btnInicioParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioParadaActionPerformed(evt);
            }
        });

        taLog.setEditable(false);
        taLog.setColumns(20);
        taLog.setLineWrap(true);
        taLog.setRows(5);
        taLog.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInicioParada, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarLog, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInicioParada, btnLimpiarLog});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarLog)
                    .addComponent(btnInicioParada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioParadaActionPerformed
        procesoInicioParar();
    }//GEN-LAST:event_btnInicioParadaActionPerformed

    private void btnLimpiarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLogActionPerformed
        limpiarLogs();
    }//GEN-LAST:event_btnLimpiarLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnInicioParada;
    private javax.swing.JButton btnLimpiarLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taLog;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
